import type { Course } from "../types/course";

export const COURSES: Course[] = [
  {
    id: "skilluni-icse-java",
    slug: "icse-java-class-9-10",
    title: "ICSE Computer Applications with Java (Class 9 & 10)",
    description: "Full Java course for ICSE Students by SkillUni By Abbas",
    level: "Beginner",
    thumbnail: "/images/courses/icse-java.webp",
    isPremium: false,
    lectures: [
      {
        id: "L001",
        order: 1,
        slug: "introduction-to-java",
        title: "Introduction to Computer Applications / Java",
        description:
          "Introduction to Java, Computer Applications and ICSE syllabus overview.",
        videoUrl: "",
        notesUrl: "",
        quizUrl: "",
        duration: "15 min",
        isLocked: false,
      },
      {
        id: "L002",
        order: 2,
        slug: "procedure-oriented-programming",
        title: "Procedure Oriented Programming",
        description:
          "Learn the basics of procedure-oriented programming and its concepts.",
        videoUrl: "https://www.youtube.com/watch?v=4dS-UxpC93o",
        notesUrl: "",
        quizUrl: "",
        duration: "18 min",
        isLocked: false,
      },
      {
        id: "L003",
        order: 3,
        slug: "object-oriented-programming",
        title: "Object Oriented Programming",
        description: "Understand OOP concepts, features and advantages in Java.",
        videoUrl: "https://www.youtube.com/watch?v=Bg_iLOzzxRU",
        notesUrl: "",
        quizUrl: "",
        duration: "20 min",
        isLocked: false,
      },
      {
        id: "L011",
        order: 4,
        slug: "classes-and-objects",
        title: "Classes and Objects in Java",
        description: "Learn how classes and objects work in Java programming.",
        videoUrl: "",
        notesUrl: "",
        quizUrl: "",
        duration: "22 min",
        isLocked: false,
      },
      {
        id: "L013",
        order: 5,
        slug: "ascii-code-explained",
        title: "ASCII Code Explained",
        description: "Understand ASCII encoding and how computers store characters.",
        videoUrl: "https://www.youtube.com/watch?v=x3u1de8ZPk4",
        notesUrl: "",
        quizUrl: "",
        duration: "12 min",
        isLocked: false,
      },
      {
        id: "L014",
        order: 6,
        slug: "unicode-explained",
        title: "Unicode Explained",
        description: "Learn Unicode and why it is important in modern computing.",
        videoUrl: "",
        notesUrl: "",
        quizUrl: "",
        duration: "14 min",
        isLocked: false,
      },
      {
        id: "L017",
        order: 7,
        slug: "tokens-in-java",
        title: "Tokens in Java",
        description: "Learn what tokens are and their role in Java syntax.",
        videoUrl: "https://www.youtube.com/watch?v=j8ZMFd-xK8U",
        notesUrl: "",
        quizUrl: "",
        duration: "16 min",
        isLocked: false,
      },
      {
        id: "L018",
        order: 8,
        slug: "keywords-in-java",
        title: "Keywords in Java",
        description: "Understand Java keywords and their significance.",
        videoUrl: "https://www.youtube.com/watch?v=X5juJUBj4Wk",
        notesUrl: "",
        quizUrl: "",
        duration: "14 min",
        isLocked: false,
      },
      {
        id: "L019",
        order: 9,
        slug: "identifiers-in-java",
        title: "Identifiers in Java",
        description: "Learn naming rules and conventions for identifiers in Java.",
        videoUrl: "",
        notesUrl: "",
        quizUrl: "",
        duration: "12 min",
        isLocked: false,
      },
      {
        id: "L020",
        order: 10,
        slug: "literals-in-java",
        title: "Literals in Java",
        description: "Understand literals and their different types in Java.",
        videoUrl: "",
        notesUrl: "",
        quizUrl: "",
        duration: "13 min",
        isLocked: false,
      },
      {
        id: "L027",
        order: 11,
        slug: "logical-operators-in-java",
        title: "Logical Operators in Java",
        description:
          "Learn AND, OR, NOT operators and logical expressions in Java.",
        videoUrl: "https://www.youtube.com/watch?v=HwyXfgYQCPU",
        notesUrl: "",
        quizUrl: "",
        duration: "17 min",
        isLocked: false,
      },
    ],
  },
];
